apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-config
  namespace: 5g-core
data:
  amf.yaml: |
    logger:
      file:
        path: amf.log
    amf:
      amf_name: open5gs-amf
      time:
        t3512:
          value: 5400
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          scp:
            - uri: http://scp-svc:7777
      ngap:
        server:
          - address: 0.0.0.0
      guami:
        - plmn_id:
            mcc: 999
            mnc: 70
          amf_id:
            region: 2
            set: 1
      tai:
        - plmn_id:
            mcc: 999
            mnc: 70
          tac: 1
      plmn_support:
        - plmn_id:
            mcc: 999
            mnc: 70
          s_nssai:
            - sst: 1
      security:
        integrity_order:
          - NIA2
          - NIA1
          - NIA0
        ciphering_order:
          - NEA0
          - NEA1
          - NEA2
      network_name:
        full: Open5GS
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smf-config
  namespace: 5g-core
data:
  smf.yaml: |
    logger:
      file:
        path: smf.log
    smf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          scp:
            - uri: http://scp-svc:7777
      pfcp:
        server:
          - address: 0.0.0.0
        client:
          upf:
            - address: upf-svc
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
          dnn: internet
      dns:
        - 8.8.8.8
        - 8.8.4.4
      mtu: 1400
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: upf-config
  namespace: 5g-core
data:
  upf.yaml: |
    logger:
      file:
        path: upf.log
    upf:
      pfcp:
        server:
          - address: 0.0.0.0
      gtpu:
        server:
          - address: 0.0.0.0
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
          dnn: internet
      tunnel_interface:
        name: ogstun
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-config
  namespace: 5g-core
data:
  nrf.yaml: |
    logger:
      file:
        path: nrf.log
    nrf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scp-config
  namespace: 5g-core
data:
  scp.yaml: |
    logger:
      file:
        path: scp.log
    scp:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://nrf-svc:7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-config
  namespace: 5g-core
data:
  ausf.yaml: |
    logger:
      file:
        path: ausf.log
    ausf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          scp:
            - uri: http://scp-svc:7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udm-config
  namespace: 5g-core
data:
  udm.yaml: |
    logger:
      file:
        path: udm.log
    udm:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          scp:
            - uri: http://scp-svc:7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-config
  namespace: 5g-core
data:
  pcf.yaml: |
    logger:
      file:
        path: pcf.log
    pcf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          scp:
            - uri: http://scp-svc:7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-config
  namespace: 5g-core
data:
  nssf.yaml: |
    logger:
      file:
        path: nssf.log
    nssf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          scp:
            - uri: http://scp-svc:7777  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bsf-config
  namespace: 5g-core
data:
  bsf.yaml: |
    logger:
      file:
        path: bsf.log
    bsf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          scp:
            - uri: http://scp-svc:7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udr-config
  namespace: 5g-core
data:
  udr.yaml: |
    logger:
      file:
        path: udr.log
    udr:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          scp:
            - uri: http://scp-svc:7777